# -*- coding: utf-8 -*-
"""Data Collection and Acquisition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-tXdckOiTeCNdEL2GgB8amLjCILQMHC5
"""

import os


os.environ["KAGGLE_USERNAME"] = "siddharthsami"
os.environ["KAGGLE_KEY"] = "KGAT_b65dedeb97a2f71d0dfe069e4c0cc4b1"

import hashlib
import pandas as pd
from kaggle.api.kaggle_api_extended import KaggleApi

api = KaggleApi()
api.authenticate()

DATASET_SLUG = "ratin21/nba-player-stats-and-salaries-2000-2025"
DOWNLOAD_PATH = DOWNLOAD_PATH = os.path.join(os.getcwd(), "data")
os.makedirs(DOWNLOAD_PATH, exist_ok=True)


DOWNLOAD_PATH_SEASONS = r"C:\Users\siddh\OneDrive\Desktop\IS377 Project\Data"
season_data = os.path.join(DOWNLOAD_PATH_SEASONS, "Season_Data_Sheet1.csv")

print(f"Downloading dataset '{DATASET_SLUG}'...")
api.dataset_download_files(DATASET_SLUG, path=DOWNLOAD_PATH, unzip=True)
print("Download complete!")

if os.path.exists(season_data):
    df_season = pd.read_csv(season_data)
    print("Preview of seasons CSV:")
    print(df_season.head())
else:
    print(f"Seasons CSV not found at {season_data}, skipping load.")

def sha256_checksum(file_path):
    sha256 = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256.update(chunk)
    return sha256.hexdigest()

print("Computing SHA-256 checksums...")
checksums = []
for root, dirs, files in os.walk(DOWNLOAD_PATH):
    for file in files:
        file_path = os.path.join(root, file)
        checksum = sha256_checksum(file_path)
        checksums.append((file, checksum))
        print(f"{file}: {checksum}")

checksums_file = os.path.join(DOWNLOAD_PATH, "checksums.txt")
with open(checksums_file, "w") as f:
    for file, checksum in checksums:
        f.write(f"{file}: {checksum}\n")
print(f"All checksums saved to {checksums_file}")

print("Files in data folder:")
for f in os.listdir(DOWNLOAD_PATH):
    print(f)